In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
x=np.array([1,0,0,0])
print("original array")
print(x)
print(np.any(x))
x=np.array([0,0,0,0,])
print(np.any(x))

original array
[1 0 0 0]
True
False


In [ ]:
import numpy as np
a=np.array([1,0,np.nan,np.inf])
print(a)
print("test element wise for nan")
print(np.isnan(a))

[ 1.  0. nan inf]
test element wise for nan
[False False  True False]


In [ ]:
import numpy as np
a=np.array([1,-2,np.inf,-np.inf,0,3.5])
result_pinf=np.isposinf(a)
result_ninf=np.isneginf(a)
print("result at pos inf",result_pinf)
print("result at neg inf",result_ninf)

result at pos inf [False False  True False False False]
result at neg inf [False False False  True False False]


In [ ]:
import numpy as np
a=np.arange(30,71,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


import numpy as np
a=np.identity(7)
print("7x7 matrix")
print(a)

In [ ]:

import numpy as np
a= np.matrix('[4, 1; 12, 3]')
b= a.sum()

print(b)

20


In [ ]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

arr_result = np.multiply(arr1, arr2)

print(arr_result)


[[ 5 12]
 [21 32]]


In [ ]:
import numpy as np
array=([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])
print(np.transpose(array))

[[ 0.  3.  6.]
 [ 2.  5.  8.]
 [ 4.  7. 10.]]


import numpy as np
array=([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])
print(array)
print(array[::-1])

In [ ]:
import numpy as np
a=np.array([[ 0,  2,  4, 5],
            [ 3,  5,  7, 6],
            [ 6,  8, 10, 2],
            [ 5,  2, 8,  0]])
new_array = a[:, ::-1]
print(new_array)

[[ 5  4  2  0]
 [ 6  7  5  3]
 [ 2 10  8  6]
 [ 0  8  2  5]]
